---
- name: "Populate Netbox Data"
  connection: local
  hosts: localhost
  gather_facts: False
  vars:
    net_url: "http://localhost"
    net_token: "3cae8e837546ef3105bb8ff64309025cc37216a4"
    device_roles:
      - ios
      - dellos10
    manu:
      - Dell
      - Cisco
    device_types:
      - name: "Dell_5224_ON"
        manufacturer: "Dell"
        part_number: "5224_on"
        u_height: 1
        is_full_depth: False
      - name: "Cisco_7200"
        manufacturer: "Cisco"
        part_number: "7200_big"
        u_height: 2
        is_full_depth: False

  tasks:
    - name: Create site within Netbox
      netbox_site:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          name: "3_node_demo_topology"
          slug: "3_node_demo_topology"
        state: present

    - name: Create roles within Netbox
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          name: "{{ item }}"
          color: "2196f3"
        state: present
      with_items: "{{ device_roles }}"

    - name: Create manufacturer within Netbox with only required information
      netbox.netbox.netbox_manufacturer:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          name: "{{ item }}"
        state: present
      with_items: "{{ manu }}"

    - name: Create device type within Netbox with only required information
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          model: "{{ item.name }}"
          manufacturer: "{{ item.manufacturer }}"
          part_number: "{{ item.part_number }}"
          u_height: "{{ item.u_height }}"
          is_full_depth: "{{ item.is_full_depth }}"
        state: present
      with_items: "{{ device_types }}"

    - name: Create platform within Netbox with only required information
      netbox.netbox.netbox_platform:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          name: "{{ item }}"
          napalm_driver: "{{ item }}"
          napalm_args:
            secret: "admin"
        state: present
      with_items: "{{ device_roles }}"

    - name: Create interface template for Dell_5224_ON
      netbox.netbox.netbox_device_interface_template:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          device_type: "Dell_5224_ON"
          name: "ethernet1/1/{{ item }}"
          type: 1000BASE-T (1GE)
        state: present
      with_sequence: 1-28

    - name: Create interface template for Dell_5224_ON mgmt
      netbox.netbox.netbox_device_interface_template:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          device_type: "Dell_5224_ON"
          name: "management1/1/1"
          type: 1000BASE-T (1GE)
          mgmt_only: True
        state: present

    - name: Create interface template for Dell_5224_ON mgmt
      netbox.netbox.netbox_device_interface_template:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          device_type: "Cisco_7200"
          name: "{{ item.name }}"
          type: "{{ item.type }}"
          mgmt_only: "{{ item.mgmt_only }}"
        state: present
      with_items:
        - name: "FastEthernet0/0"
          type: 100BASE-TX (10/100ME)
          mgmt_only: True
        - name: "GigabitEthernet0/0"
          type: 1000BASE-T (1GE)
          mgmt_only: False

    - name: Create Dell Device in Netbox
      netbox.netbox.netbox_device:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          name: "Dell-5224-{{ item }}"
          device_type: "Dell_5224_ON"
          device_role: "dellos10"
          site: "3_node_demo_topology"
          platform: "dellos10"
        state: present
      with_sequence: 1-2

    - name: Create Cisco Device in Netbox
      netbox.netbox.netbox_device:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          name: "Cisco_7200_1"
          device_type: "Cisco_7200"
          device_role: "ios"
          site: "3_node_demo_topology"
          platform: "ios"
        state: present

    - name: Attach a new available IP to Dell-1 management1/1/1
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          address: 192.168.1.155/24
          assigned_object:
            name: management1/1/1
            device: Dell-5224-1
        state: present

    - name: Attach a new available IP to Dell-2 management1/1/1
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          address: 192.168.1.157/24
          assigned_object:
            name: management1/1/1
            device: Dell-5224-2
        state: present

    - name: Attach a new available IP to Cisco FastEthernet0/0
      netbox.netbox.netbox_ip_address:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          address: 192.168.1.154/24
          assigned_object:
            name: FastEthernet0/0
            device: Cisco_7200_1
        state: present

    - name: Append Primary IP to Dell Device in Netbox
      netbox.netbox.netbox_device:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          name: "Dell-5224-1"
          primary_ip4: "192.168.1.155/24"
        state: present

    - name: Append Primary IP to Dell Device in Netbox
      netbox.netbox.netbox_device:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          name: "Dell-5224-2"
          primary_ip4: "192.168.1.157/24"
        state: present

    - name: Append Primary IP to  Cisco Device in Netbox
      netbox.netbox.netbox_device:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          name: "Cisco_7200_1"
          primary_ip4: "192.168.1.154/24"
        state: present

    - name: Create cable plan within Netbox for demo
      netbox.netbox.netbox_cable:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          termination_a_type: dcim.interface
          termination_a:
            device: Dell-5224-1
            name: ethernet1/1/5
          termination_b_type: dcim.interface
          termination_b:
            device: Dell-5224-2
            name: ethernet1/1/5
        state: present

    - name: Create cable plan within Netbox for demo
      netbox.netbox.netbox_cable:
        netbox_url: "{{ net_url }}"
        netbox_token: "{{ net_token }}"
        data:
          termination_a_type: dcim.interface
          termination_a:
            device: Dell-5224-1
            name: ethernet1/1/6
          termination_b_type: dcim.interface
          termination_b:
            device: Dell-5224-2
            name: ethernet1/1/6
        state: present
